"""Your migration message

Revision ID: f47e535fa912
Revises: 
Create Date: 2025-02-14 17:23:45.024895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f47e535fa912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('difficulty_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('job_url', sa.String(length=255), nullable=True),
    sa.Column('recruiter_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewer_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onsite_interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('onsite_date', sa.DateTime(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('phone_screen_date', sa.DateTime(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('AllUnique2', schema=None) as batch_op:
        batch_op.drop_index('ind')

    op.drop_table('AllUnique2')
    op.drop_table('SriramList2')
    op.drop_table('work')
    with op.batch_alter_table('whatsapp', schema=None) as batch_op:
        batch_op.drop_index('whatsappind')

    op.drop_table('whatsapp')
    op.drop_table('icertportalbackup')
    with op.batch_alter_table('finalList', schema=None) as batch_op:
        batch_op.drop_index('ind')

    op.drop_table('finalList')
    with op.batch_alter_table('AlexList', schema=None) as batch_op:
        batch_op.drop_index('ind')

    op.drop_table('AlexList')
    with op.batch_alter_table('stockdata_top_5day', schema=None) as batch_op:
        batch_op.drop_index('stockdata_top_5day_idx')

    op.drop_table('stockdata_top_5day')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('courses_uidx1')

    op.drop_table('courses')
    with op.batch_alter_table('finalList2', schema=None) as batch_op:
        batch_op.drop_index('ind')

    op.drop_table('finalList2')
    op.drop_table('college')
    op.drop_table('bothList')
    op.drop_table('message')
    with op.batch_alter_table('AllHosts', schema=None) as batch_op:
        batch_op.drop_index('ind')

    op.drop_table('AllHosts')
    op.drop_table('counts')
    op.drop_table('stock_ma')
    op.drop_table('icertportal')
    op.drop_table('rackempcopy')
    op.drop_table('SriramList')
    with op.batch_alter_table('stockdata', schema=None) as batch_op:
        batch_op.drop_index('stockind')

    op.drop_table('stockdata')
    with op.batch_alter_table('stockdata_daily_cp', schema=None) as batch_op:
        batch_op.drop_index('stockind_cp')

    op.drop_table('stockdata_daily_cp')
    op.drop_table('remainingServers')
    op.drop_table('countingProfile')
    with op.batch_alter_table('remaining2', schema=None) as batch_op:
        batch_op.drop_index('finalList')
        batch_op.drop_index('ind')

    op.drop_table('remaining2')
    with op.batch_alter_table('stockdata_daily', schema=None) as batch_op:
        batch_op.drop_index('stockind')

    op.drop_table('stockdata_daily')
    op.drop_table('index_ticker')
    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.drop_index('dividend_idx')

    op.drop_table('dividend')
    op.drop_table('Customer')
    op.drop_table('location')
    op.drop_table('DefectiveDevice')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ind')

    op.drop_table('expenses')
    op.drop_table('rackemp')
    op.drop_table('AllUnique')
    with op.batch_alter_table('expenses_test', schema=None) as batch_op:
        batch_op.drop_index('ind')

    op.drop_table('expenses_test')
    op.drop_table('ArunList')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index('arkk_ui')

    op.drop_table('stocks')
    op.drop_table('ArunsList1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArunsList1',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('stocks',
    sa.Column('created_date', sa.DATE(), nullable=True),
    sa.Column('fund', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('company', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('ticker', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('cuisp', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('shares', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MARKET_VALUE', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('weight', mysql.FLOAT(precision=5, scale=2), nullable=True),
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('arkk_ui', ['created_date', 'fund', 'company', 'ticker', 'shares'], unique=True)

    op.create_table('ArunList',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('expenses_test',
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('item', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=500), nullable=True),
    sa.Column('comment', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=1000), nullable=True),
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('expenses_test', schema=None) as batch_op:
        batch_op.create_index('ind', ['created_date', 'item'], unique=True)

    op.create_table('AllUnique',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('rackemp',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('designation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ext', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hiredate', sa.DATE(), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('boss', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('left_t', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('expenses',
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('item', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=500), nullable=True),
    sa.Column('comment', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=1000), nullable=True),
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ind', ['created_date', 'item', 'amount'], unique=True)

    op.create_table('DefectiveDevice',
    sa.Column('created_t', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deviceNumber', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('imei', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dateFound', sa.DATE(), nullable=True),
    sa.Column('reason', mysql.VARCHAR(length=4000), nullable=True),
    sa.Column('returnToManufacture', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('manufacturerAgreedToReplace', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expectedReplacementDate', sa.DATE(), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('location',
    sa.Column('created_t', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('CustomerID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BusinessName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('businessType', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('State', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Country', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ZipCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('PhoneNumber', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Facebook', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Twitter', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Google', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Latitude', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('Longitude', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('BusinessID', mysql.VARCHAR(length=30), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('Customer',
    sa.Column('created_t', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('State', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Country', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Zip', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('Phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Facebook', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Twitter', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Google', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('customerID', mysql.INTEGER(), autoincrement=False, nullable=False),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('dividend',
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('payment_Date', sa.DATE(), nullable=True),
    sa.Column('record_Date', sa.DATE(), nullable=True),
    sa.Column('dividend_Ex_Date', sa.DATE(), nullable=True),
    sa.Column('announcement_Date', sa.DATE(), nullable=True),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('dividend_Rate', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('indicated_Annual_Dividend', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.create_index('dividend_idx', ['payment_Date', 'symbol'], unique=True)

    op.create_table('index_ticker',
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('sector', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sub_industry', mysql.VARCHAR(length=100), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('stockdata_daily',
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('lastsale', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('netchange', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('pctchange', mysql.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('market_cap', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_date', sa.DATE(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stockdata_daily', schema=None) as batch_op:
        batch_op.create_index('stockind', ['ts', 'symbol', 'netchange', 'pctchange'], unique=True)

    op.create_table('remaining2',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('assignee', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=200), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('remaining2', schema=None) as batch_op:
        batch_op.create_index('ind', ['hostname', 'IP'], unique=True)
        batch_op.create_index('finalList', ['hostname', 'IP'], unique=True)

    op.create_table('countingProfile',
    sa.Column('created_t', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('CustomerID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BusinessID', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('countingProfileName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('countingMeasure', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('button1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('button2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('button3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('button4', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('countingProfileID', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('remainingServers',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('stockdata_daily_cp',
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('lastsale', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('netchange', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('pctchange', mysql.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('market_cap', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_date', sa.DATE(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stockdata_daily_cp', schema=None) as batch_op:
        batch_op.create_index('stockind_cp', ['ts', 'symbol', 'netchange', 'pctchange'], unique=False)

    op.create_table('stockdata',
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('lastsale', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('netchange', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('pctchange', mysql.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('market_cap', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_date', sa.DATE(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stockdata', schema=None) as batch_op:
        batch_op.create_index('stockind', ['created_date', 'symbol', 'netchange', 'pctchange'], unique=True)

    op.create_table('SriramList',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('assignee', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=200), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('rackempcopy',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('designation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ext', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hiredate', sa.DATE(), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('boss', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('left_t', mysql.TIMESTAMP(), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('icertportal',
    sa.Column('created_t', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('caseNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('jobPostingDate', sa.DATE(), nullable=True),
    sa.Column('caseType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('employer', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=True),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.Column('jobTitle', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('caseNumber'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('stock_ma',
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('fifty_day_ma', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('twentyone_day_ma', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('fifty_dayavg', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('twentyone_dayavg', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('counts',
    sa.Column('created_t', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('imei', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('button1Count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('button2Count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('button3Count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('button4Count', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('AllHosts',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('AllHosts', schema=None) as batch_op:
        batch_op.create_index('ind', ['hostname', 'IP'], unique=True)

    op.create_table('message',
    sa.Column('created_t', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('imei', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('messageType', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('longitude', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('latitude', mysql.VARCHAR(length=11), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('bothList',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('college',
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('created_ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('finalList2',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('OS', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('assignee', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=300), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('finalList2', schema=None) as batch_op:
        batch_op.create_index('ind', ['hostname', 'IP'], unique=True)

    op.create_table('courses',
    sa.Column('track', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('course', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('college', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mandatory', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('credits', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('semester', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('required_courses', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alternate_course', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('required_sub_course', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('electives_course', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('courses_uidx1', ['track', 'course', 'electives_course'], unique=True)

    op.create_table('stockdata_top_5day',
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('pctgrowth', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stockdata_top_5day', schema=None) as batch_op:
        batch_op.create_index('stockdata_top_5day_idx', ['symbol', 'pctgrowth', 'rank'], unique=True)

    op.create_table('AlexList',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('OS', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Env', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('AlexList', schema=None) as batch_op:
        batch_op.create_index('ind', ['hostname', 'IP'], unique=True)

    op.create_table('finalList',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('OS', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('assignee', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=200), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('finalList', schema=None) as batch_op:
        batch_op.create_index('ind', ['hostname', 'IP'], unique=True)

    op.create_table('icertportalbackup',
    sa.Column('created_t', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('caseNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('jobPostingDate', sa.DATE(), nullable=True),
    sa.Column('caseType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('employer', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=True),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.Column('jobTitle', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('whatsapp',
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=50), nullable=True),
    sa.Column('text', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=1000), nullable=True),
    sa.Column('comment', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=True),
    sa.Column('textlen', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ts', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('groupname', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('whatsapp', schema=None) as batch_op:
        batch_op.create_index('whatsappind', ['created_date', 'name', 'textlen'], unique=True)

    op.create_table('work',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('OS', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('STatus', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Assignee', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Issues', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Comments', mysql.VARCHAR(length=100), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('SriramList2',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('OS', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('assignee', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=200), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('AllUnique2',
    sa.Column('hostname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('OS', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('assignee', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=200), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('AllUnique2', schema=None) as batch_op:
        batch_op.create_index('ind', ['hostname', 'IP'], unique=True)

    op.drop_table('phone_screen')
    op.drop_table('onsite_interview')
    op.drop_table('interviewer_comment')
    op.drop_table('interview')
    op.drop_table('user')
    op.drop_table('interviewer')
    # ### end Alembic commands ###
